--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigcrafter/KygekJoinUI
build-by-default: true
branches:
- main
projects:
  KygekJoinUI:
    path: ""
    libs:
    - src: Vecnavium/FormsUI/FormsUI
      version: ^1.1.2
    - src: thebigcrafter/Hydrogen/Hydrogen
      version: ^1.0.0
...
