--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekJoinUI
build-by-default: true
branches:
- master
- pm4
projects:
  KygekJoinUI:
    path: ""
    libs:
    - src: Vecnavium/FormsUI/FormsUI
      version: ^1.0.0
    - src: KygekTeam/ktpmpl-cfs/ktpmpl-cfs
      version: ^4.0.0
...
